# Index Management
df.reset_index()
df.set_index()
df.sort_index()

In [1]:
# Import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

/opt/anaconda3/envs/python_beginner_course/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
425175,Senior Data Scientist,Senior Data Scientist,United States,via BeBee,Full-time,False,"Illinois, United States",2023-11-20 16:04:24,False,False,United States,NaN,NaN,NaN,Peraton,"['python', 'scala', 'css', 'html', 'databricks...","{'cloud': ['databricks', 'aws', 'redshift'], '..."
762775,Business Analyst,Payroll Analyst - Hiring Urgently,"Quezon City, Metro Manila, Philippines",via GrabJobs,Full-time,False,Philippines,2023-11-20 20:09:22,False,False,Philippines,NaN,NaN,NaN,Chevron,['sap'],{'analyst_tools': ['sap']}
26096,Data Engineer,Project Engineer - Automation /Mechanical/Mech...,"Brussels, Belgium",via LinkedIn,Full-time,False,Belgium,2023-07-06 13:35:03,False,False,Belgium,NaN,NaN,NaN,Procter & Gamble,NaN,NaN
247033,Data Engineer,Data Science Engineer,"Germantown, MD",via LinkedIn,Full-time,False,"New York, United States",2023-12-07 07:03:32,False,False,United States,NaN,NaN,NaN,RICEFW Technologies Inc,"['python', 'r', 'sql', 'aws', 'bigquery', 'pan...","{'analyst_tools': ['tableau'], 'cloud': ['aws'..."
600543,Data Analyst,Data Analist,"Eindhoven, Netherlands",via BeBee,Full-time,False,Netherlands,2023-10-22 09:42:44,True,False,Netherlands,NaN,NaN,NaN,Careervalue,['power bi'],{'analyst_tools': ['power bi']}

In [4]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [5]:
df.index.name = 'job_index'

In [6]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
100925,Data Engineer,Data engineer,"Dallas, TX",via Talent.com,Full-time,False,Georgia,2023-12-27 00:28:44,True,False,United States,NaN,NaN,NaN,ENGIE Laborelec,NaN,NaN
767614,Software Engineer,Engineering Manager (Data Software Engineering...,"Paris, France",via Startup Jobs,Full-time,False,France,2023-01-12 01:14:31,False,False,France,NaN,NaN,NaN,M33 Startup Studio,NaN,NaN
495118,Data Engineer,"Data Engineer,","Rochdale, UK",via BeBee,Full-time,False,United Kingdom,2023-10-13 11:36:55,True,False,United Kingdom,NaN,NaN,NaN,Hackajob Ltd,"['sql', 'python', 'gcp', 'aws', 'azure', 'snow...","{'cloud': ['gcp', 'aws', 'azure', 'snowflake',..."
246439,Software Engineer,"Senior Software Engineer, Backend (Claims)","Tel Aviv-Yafo, Israel",via Melga,Full-time,False,Israel,2023-02-23 08:16:00,True,False,Israel,NaN,NaN,NaN,Fairmatic,"['python', 'postgresql', 'aws', 'flask', 'djan...","{'cloud': ['aws'], 'databases': ['postgresql']..."
485126,Data Analyst,Data Analyst/ Assistant Data Analyst,Hong Kong,via EC Healthcare Careers Center,Full-time,False,Hong Kong,2023-01-11 14:33:56,False,False,Hong Kong,NaN,NaN,NaN,EC Healthcare,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [7]:
df.index.dtype

dtype('int64')

In [19]:
df_usa = df[df['job_country'] == 'United States']
df_usa.head(5)
#Now the job_index is messed up

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [20]:
#reset the index
df_usa.reset_index(inplace =True)
df_usa.head(5)

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [21]:
# now we can use a specific column as the index, for now lets use the job_index
df_usa.set_index('job_index', inplace=True)
df_usa.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

sort_index()
* useful when using a pivot table

In [23]:
#Lets say we built a pivot table
median_pivot = df_usa.pivot_table(values= 'salary_year_avg', index='job_title_short', aggfunc=['median','mean','max'])
median_pivot

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0    96175.447397        387460.0
Cloud Engineer                   116100.0   120090.900000        221844.0
Data Analyst                      90000.0    94553.964924        375000.0
Data Engineer                    125000.0   134226.676753        525000.0
Data Scientist                   130000.0   139946.707204        960000.0
Machine Learning Engineer        150000.0   154240.382812        315000.0
Senior Data Analyst              110000.0   115729.129954        425000.0
Senior Data Engineer             150000.0   151448.023186        375000.0
Senior Data Scientist            155000.0   159330.432029        475000.0
Software Engineer                130000.0   137964.929588        375000.0

In [28]:
#Let say we sort it by median
median_pivot = median_pivot.sort_values(('median', 'salary_year_avg'), ascending=False)
median_pivot

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155000.0   159330.432029        475000.0
Machine Learning Engineer        150000.0   154240.382812        315000.0
Senior Data Engineer             150000.0   151448.023186        375000.0
Data Scientist                   130000.0   139946.707204        960000.0
Software Engineer                130000.0   137964.929588        375000.0
Data Engineer                    125000.0   134226.676753        525000.0
Cloud Engineer                   116100.0   120090.900000        221844.0
Senior Data Analyst              110000.0   115729.129954        425000.0
Business Analyst                  90000.0    96175.447397        387460.0
Data Analyst                      90000.0    94553.964924        375000.0

In [ ]:
#But then we want to sort it back as alphebetical order by job title
median_pivot.sort_index(inplace=True)

In [30]:
median_pivot

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0    96175.447397        387460.0
Cloud Engineer                   116100.0   120090.900000        221844.0
Data Analyst                      90000.0    94553.964924        375000.0
Data Engineer                    125000.0   134226.676753        525000.0
Data Scientist                   130000.0   139946.707204        960000.0
Machine Learning Engineer        150000.0   154240.382812        315000.0
Senior Data Analyst              110000.0   115729.129954        425000.0
Senior Data Engineer             150000.0   151448.023186        375000.0
Senior Data Scientist            155000.0   159330.432029        475000.0
Software Engineer                130000.0   137964.929588        375000.0