# Modules


*   Like a file of pre-defined functions
*   The Python Standard Library provides a lot of modules
*  e.g. maths, staistics, etc.
* https://docs.python.org/3/library/index.html

import modules

In [ ]:
from statistics import mean, median, mode

number_list = [10000, 20000, 30000, 40000, 40000]

mean(number_list)

28000

In [ ]:
median(number_list)

30000

In [ ]:
mode(number_list)

40000

Clear dataset by using modules


*   turn string into datetime
*   turn string into a list

In [ ]:
from datetime import datetime
import ast

datetime.now()

datetime.datetime(2026, 8, 14, 9, 20, 16, 240561)

In [ ]:
data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-15'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-08'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'}
]

In [ ]:
for job in data_science_jobs:
  job['job_date'] = datetime.strptime(job['job_date'], '%Y-%m-%d')
  job['job_skills'] = ast.literal_eval(job['job_skills'])

In [ ]:
data_science_jobs

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'SQL', 'Machine Learning'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Deep Learning'],
  'job_date': datetime.datetime(2023, 5, 15, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': ['SQL', 'R', 'Tableau'],
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': ['SQL', 'PowerBI', 'Data Warehousing'],
  'job_date': datetime.datetime(2023, 5, 8, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': ['Python', 'Spark', 'Hadoop'],
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': ['Python', 'PyTorch', 'AI Ethics'],
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

#Libraies

* Module: a file with functions in it
* Package: a file with modules in it
* Library: a file with packages and modules in it
* can be found in pipy/ conda/ python standard library

# Pandas


*   A library useful for data analysis

Install pandas

In [ ]:
!pip list
#check if pandas is already in the environment, if not type !pip install panda

Package                               Version
------------------------------------- ------------------
absl-py                               1.4.0
accelerate                            1.14.0
access                                1.1.10.post3
affine                                2.4.0
aiofiles                              25.1.0
aiohappyeyeballs                      2.7.1
aiohttp                               3.14.1
aiosignal                             1.4.0
aiosqlite                             0.22.1
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.12.0
altair                                5.5.0
annotated-doc                         0.0.4
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.14.2
anywidget                             0.9.21
apsw                                  3.53.3.1
apswutils                             0.1.2
argon2-cffi                           25.1.0
argon2-cffi-bindings                  25.1.0
array_record                          0.8.3
arrow                                 1.4.0
arviz                                 0.22.0
astropy                               7.2.2
astropy-iers-data                     0.2026.7.13.0.54.2
astunparse                            1.6.3
atpublic                              5.1
attrs                                 26.1.0
audioread                             3.1.0
Authlib                               1.7.2
autograd                              1.9.1
babel                                 2.18.0
backcall                              0.2.0
beartype                              0.22.9
beautifulsoup4                        4.13.5
betterproto                           2.0.0b6
bigframes                             2.42.0
bigquery-magics                       0.14.0
bleach                                6.4.0
blinker                               1.9.0
blis                                  1.3.3
blobfile                              3.2.0
blosc2                                4.8.0
bokeh                                 3.8.2
Bottleneck                            1.4.2
bqplot                                0.12.47
branca                                0.8.2
brotli                                1.2.0
CacheControl                          0.14.4
cachetools                            6.2.6
catalogue                             2.0.10
certifi                               2026.6.17
cffi                                  2.1.0
chardet                               5.2.0
charset-normalizer                    3.4.9
clarabel                              0.11.1
click                                 8.4.2
cligj                                 0.7.2
cloudpathlib                          0.24.0
cloudpickle                           3.1.2
cmake                                 3.31.10
cmdstanpy                             1.3.0
colorcet                              3.2.1
colorlover                            0.3.0
community                             1.0.0b1
confection                            1.3.3
cons                                  0.4.7
contourpy                             1.3.3
cramjam                               2.11.0
cryptography                          49.0.0
cufflinks                             0.17.3
curl_cffi                             0.15.0
cvxopt                                1.3.2
cvxpy                                 1.6.7
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.13
Cython                                3.0.12
dask                                  2026.7.0
dataproc-spark-connect                1.1.0
datasets                              4.0.0
db-dtypes                             1.7.1
dbus-python                           1.2.18
debugpy                               1.8.15
decorator                             4.4.2
defusedxml                            0.7.1
deprecation                           2.1.0
diffusers                             0.39.0
dill                                  0.3.8
distro                                1.9.0
dlib                                  19.24.6
dm-tree                               0.1.10
docstring_parser                      0.18.0
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.3.2
earthengine-api                       1.7.35
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.2
einops                                0.8.2
en_core_web_sm                        3.8.0
entrypoints                           0.4
esda                                  2.9.0
et_xmlfile                            2.0.0
etils                                 1.14.0
etuples                               0.3.10
Farama-Notifications                  0.0.6
fastai                                2.8.7
fastapi                               0.139.0
fastcore                              2.0.5
fastdownload                          0.0.7
fastjsonschema                        2.21.2
fastlite                              0.2.4
fastprogress                          1.1.6
fasttransform                         0.0.2
filelock                              3.29.7
firebase-admin                        6.9.0
Flask                                 3.1.3
flatbuffers                           25.12.19
flax                                  0.11.2
folium                                0.20.0
fonttools                             4.63.0
fqdn                                  1.5.1
frozendict                            2.4.7
frozenlist                            1.8.0
fsspec                                2025.3.0
future                                1.0.0
gast                                  0.7.0
gcsfs                                 2025.3.0
GDAL                                  3.8.4
gdown                                 5.2.2
geemap                                0.38.3
geocoder                              1.38.1
geographiclib                         2.1
geopandas                             1.1.4
geopy                                 2.4.1
giddy                                 2.3.6
gin-config                            0.5.0
gitdb                                 4.0.12
GitPython                             3.1.51
glob2                                 0.7
google                                3.0.0
google-adk                            2.4.0
google-ai-generativelanguage          0.6.15
google-api-core                       2.30.3
google-api-python-client              2.198.0
google-auth                           2.49.0
google-auth-httplib2                  0.4.0
google-auth-oauthlib                  1.4.0
google-cloud-bigquery                 3.42.2
google-cloud-bigquery-connection      1.22.0
google-cloud-bigquery-storage         2.39.0
google-cloud-core                     2.6.0
google-cloud-dataproc                 5.28.0
google-cloud-datastore                2.25.0
google-cloud-firestore                2.27.0
google-cloud-functions                1.24.0
google-cloud-language                 2.21.0
google-cloud-monitoring               2.31.0
google-cloud-resource-manager         1.18.0
google-cloud-spanner                  3.68.0
google-cloud-storage                  3.13.0
google-cloud-translate                3.27.0
google-colab                          1.0.0
google-crc32c                         1.8.0
google-genai                          2.11.0
google-generativeai                   0.8.6
google-pasta                          0.2.0
google-resumable-media                2.10.0
googleapis-common-protos              1.75.0
googledrivedownloader                 1.1.0
gradio                                6.20.0
gradio_client                         2.5.0
grain                                 0.2.18
graphviz                              0.21
greenlet                              3.5.3
groovy                                0.1.2
grpc-google-iam-v1                    0.14.4
grpc-interceptor                      0.15.4
grpcio                                1.82.1
grpcio-status                         1.71.2
grpclib                               0.4.9
gspread                               6.2.1
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.1.0
gymnasium                             1.3.0
h11                                   0.16.0
h2                                    4.3.0
h5netcdf                              1.8.1
h5py                                  3.16.0
hdbscan                               0.8.44
hf-gradio                             0.4.1
hf-xet                                1.5.1
highspy                               1.15.1
holidays                              0.100
holoviews                             1.23.1
hpack                                 4.2.0
html5lib                              1.1
httpcore                              1.0.9
httpcore2                             2.5.0
httpimport                            1.4.1
httplib2                              0.32.0
httptools                             0.8.0
httpx                                 0.28.1
httpx2                                2.5.0
huggingface_hub                       1.23.0
humanize                              4.16.0
hyperframe                            6.1.0
hyperopt                              0.2.7
ibis-framework                        9.5.0
idna                                  3.18
ImageIO                               2.37.3
imageio-ffmpeg                        0.6.0
imagesize                             2.0.0
imbalanced-learn                      0.14.2
immutabledict                         4.3.1
importlib_metadata                    9.0.0
importlib_resources                   7.1.0
imutils                               0.5.4
inequality                            1.1.2
inflect                               7.5.0
iniconfig                             2.3.0
intel-cmplr-lib-ur                    2025.3.3
intel-openmp                          2025.3.3
ipyevents                             2.0.4
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.20.0
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipywidgets                            7.7.1
isoduration                           20.11.0
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.1.2
jaraco.functools                      4.5.0
jax                                   0.7.2
jaxlib                                0.7.2
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.16.0
joblib                                1.5.3
joserfc                               1.7.3
jsonpatch                             1.33
jsonpickle                            4.1.2
jsonpointer                           3.1.1
jsonschema                            4.26.0
jsonschema-specifications             2025.9.1
jupyter_client                        7.4.9
jupyter-console                       6.6.3
jupyter_core                          5.9.1
jupyter-events                        0.12.1
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.20.0
jupyter_server                        2.20.0
jupyter_server_terminals              0.5.4
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.16
jupytext                              1.19.4
kaggle                                2.0.2
kagglehub                             1.0.2
kagglesdk                             0.1.23
keras                                 3.13.2
keras-hub                             0.26.0
keras-nlp                             0.26.0
keyring                               25.7.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.5.0
langchain                             1.3.13
langchain-core                        1.4.9
langchain-protocol                    0.0.18
langgraph                             1.2.9
langgraph-checkpoint                  4.1.1
langgraph-prebuilt                    1.1.0
langgraph-sdk                         0.4.2
langsmith                             0.10.2
lark                                  1.3.1
launchpadlib                          1.10.16
lazr.restfulclient                    0.14.4
lazr.uri                              1.0.6
lazy-loader                           0.5
libclang                              18.1.1
libpysal                              4.14.1
librosa                               0.11.0
lightgbm                              4.6.0
linkify-it-py                         2.1.0
llvmlite                              0.43.0
locket                                1.0.0
logical-unification                   0.4.7
lxml                                  6.1.1
Mako                                  1.1.3
mapclassify                           2.10.0
Markdown                              3.10.2
markdown-it-py                        4.2.0
MarkupSafe                            3.0.3
matplotlib                            3.10.0
matplotlib-inline                     0.2.2
matplotlib-venn                       1.1.2
mdit-py-plugins                       0.6.1
mdurl                                 0.1.2
mgwr                                  2.2.1
miniKanren                            1.0.5
missingno                             0.5.2
mistune                               3.3.3
mizani                                0.13.5
mkl                                   2025.3.1
ml_dtypes                             0.5.4
mlxtend                               0.23.4
mmh3                                  5.2.1
momepy                                0.11.0
more-itertools                        10.8.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.2.1
multidict                             6.7.1
multipledispatch                      1.0.0
multiprocess                          0.70.16
multitasking                          0.0.13
murmurhash                            1.0.15
music21                               9.9.2
namex                                 0.1.0
narwhals                              2.24.0
natsort                               8.4.0
nbclassic                             1.3.3
nbclient                              0.10.4
nbconvert                             7.17.1
nbformat                              5.10.4
ndindex                               1.10.1
nest-asyncio                          1.6.0
networkx                              3.6.1
nh3                                   0.3.6
nibabel                               5.4.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.60.0
numexpr                               2.14.1
numpy                                 2.0.2
nvidia-nccl-cu12                      2.30.7
oauth2client                          4.1.3
oauthlib                              3.3.1
omegaconf                             2.3.1
onemkl-license                        2025.3.1
openai                                2.45.0
opencv-contrib-python                 4.13.0.92
opencv-python                         5.0.0.93
opencv-python-headless                5.0.0.93
openpyxl                              3.1.5
opentelemetry-api                     1.42.1
opentelemetry-resourcedetector-gcp    1.12.0a0
opentelemetry-sdk                     1.42.1
opentelemetry-semantic-conventions    0.63b1
opt_einsum                            3.4.0
optax                                 0.2.8
optree                                0.19.1
orbax-checkpoint                      0.12.1
orjson                                3.11.9
ormsgpack                             1.12.2
osqp                                  1.1.3
packaging                             26.2
pandas                                2.2.2
pandas-datareader                     0.11.1
pandas-gbq                            0.30.0
pandas-stubs                          2.2.2.240909
pandocfilters                         1.5.1
panel                                 1.9.3
panel-material-ui                     0.14.0
param                                 2.4.1
parso                                 0.8.7
parsy                                 2.2
partd                                 1.4.2
patsy                                 1.0.2
peewee                                4.2.2
peft                                  0.19.1
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.3.0
pip                                   24.1.2
platformdirs                          4.10.0
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.6.0
plum-dispatch                         2.9.0
pointpats                             2.5.5
polars                                1.35.2
polars-runtime-32                     1.35.2
pooch                                 1.9.0
portpicker                            1.5.2
preshed                               3.0.13
prettytable                           3.18.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.25.0
promise                               2.3
prompt_toolkit                        3.0.52
propcache                             0.5.2
prophet                               1.3.0
proto-plus                            1.28.1
protobuf                              5.29.6
psutil                                5.9.5
psycopg2                              2.9.12
psygnal                               0.15.1
ptyprocess                            0.7.0
PuLP                                  3.3.2
py-cpuinfo                            9.0.0
py4j                                  0.10.9.9
pyarrow                               18.1.0
pyasn1                                0.6.4
pyasn1_modules                        0.4.2
pycairo                               1.29.0
pycocotools                           2.0.11
pycparser                             3.0
pycryptodomex                         3.23.0
pydantic                              2.13.4
pydantic_core                         2.46.4
pydata-google-auth                    1.9.1
pydot                                 4.0.1
pydotplus                             2.0.2
PyDrive2                              1.21.1
pydub                                 0.25.1
pyerfa                                2.0.1.5
pygame                                2.6.1
pygit2                                1.19.3
Pygments                              2.20.0
PyGObject                             3.48.2
pyiceberg                             0.11.1
PyJWT                                 2.13.0
pymc                                  5.28.5
pynndescent                           0.6.0
pyogrio                               0.13.0
pyomo                                 6.10.1
PyOpenGL                              3.1.10
pyOpenSSL                             26.3.0
pyparsing                             3.3.2
pyperclip                             1.11.0
pyproj                                3.7.2
pyroaring                             1.1.0
pysal                                 25.7

In [ ]:
import pandas as pd

Load dataset

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

We need to transform this dataset into panda

In [ ]:
df = dataset['train'].to_pandas()

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

##View data

In [ ]:
df.head(10)
#show first few lines instead of top 5 and lowest 5 as default

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [ ]:
df.tail(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df['company_name'].head(5)
#choose the specific column to view

0            Boehringer Ingelheim
1      Hewlett Packard Enterprise
2        ALPHA Augmented Services
3    Southwest Research Institute
4                 Kristina Daniel
Name: company_name, dtype: object

In [ ]:
df[['company_name', 'job_location']].head(5)
#rmb to use double [] for multiple column

                   company_name                  job_location
0          Boehringer Ingelheim                 Watertown, CT
1    Hewlett Packard Enterprise  Guadalajara, Jalisco, Mexico
2      ALPHA Augmented Services               Berlin, Germany
3  Southwest Research Institute               San Antonio, TX
4               Kristina Daniel                Washington, DC

In [ ]:
df.iloc[90:100, 0:2]
#view the specific row, and column

         job_title_short                                          job_title
90        Data Scientist                                     Data Scientist
91        Data Scientist                                     Data Scientist
92         Data Engineer            Remote - Data Engineer - Permanent - W2
93          Data Analyst       IT Finance / TBM Data Analyst - Remote | WFH
94         Data Engineer                   Data Engineer - Cloud Operations
95         Data Engineer                                      Data Engineer
96         Data Engineer                                      Data Engineer
97          Data Analyst  Systems & Data Analyst - Exploitation, Missing...
98  Senior Data Engineer                         Senior Data Engineer (AWS)
99         Data Engineer  Senior/Staff Data Engineer – Apache Spark (Jav...

Investigating the data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

Filtering

In [ ]:
df.job_title_short.unique()
#array of the job title in short

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [ ]:
df.job_title_short == 'Data Analyst'

0         False
1          True
2         False
3         False
4         False
          ...
785736    False
785737     True
785738    False
785739    False
785740    False
Name: job_title_short, Length: 785741, dtype: bool

In [ ]:
df[df.job_title_short == 'Data Analyst']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,None,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
31,Data Analyst,Stage - Data Analyst F/H,"Paris, France",via LinkedIn,Full-time and Internship,False,France,2023-10-19 13:59:31,False,False,France,None,NaN,NaN,GROUPE BON MARCHÉ : Le Bon Marché Rive Gauche ...,['sql'],{'programming': ['sql']}
34,Data Analyst,Data Analyst als Marketing Manager Automation ...,"Erlangen, Germany",via Central Illinois Proud Jobs,Full-time,False,Germany,2023-02-23 13:31:28,True,False,Germany,None,NaN,NaN,DEFACTO GmbH,['sap'],{'analyst_tools': ['sap']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None
785717,Data Analyst,Data & Analytics Architect (w/m/x),"Erfurt, Jerman",melalui LinkedIn,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,NTT DATA DACH,"['aws', 'azure']","{'cloud': ['aws', 'azure']}"
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg > 100000)]
#replace & with |, represent 'or'

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
1555,Data Analyst,Data Analyst/Engineer (M/F/D),"Aveiro, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-04-25 13:27:25,False,False,Portugal,year,111175.0,NaN,Bosch Group,"['databricks', 'spark']","{'cloud': ['databricks'], 'libraries': ['spark']}"
1681,Data Analyst,Data Analyst,"Irvine, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-03-23 13:01:14,False,True,United States,year,111175.0,NaN,Western Digital,"['sql', 'tableau', 'power bi', 'excel']","{'analyst_tools': ['tableau', 'power bi', 'exc..."
1684,Data Analyst,Data Analyst - Data17829,"Tampa, FL",via Indeed,Full-time,False,"Florida, United States",2023-07-18 13:02:09,True,True,United States,year,120000.0,NaN,Acrisure,"['shell', 'sql', 'azure', 'databricks', 'linux']","{'cloud': ['azure', 'databricks'], 'os': ['lin..."
1867,Data Analyst,Data Integration Analyst (West Coast/Chicago),"Chicago, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-07-18 13:01:47,False,False,United States,year,101500.0,NaN,Forsta,"['php', 'python', 'express']","{'programming': ['php', 'python'], 'webframewo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783588,Data Analyst,Data Analytics Manager,"Chicago, IL",via Ladders,Full-time,False,"Illinois, United States",2023-01-09 06:01:18,False,False,United States,year,125000.0,NaN,"United Air Lines, Inc","['sql', 'r', 'python', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
783866,Data Analyst,Lead Credit Bureau Data Analyst,"Des Plaines, IL",via Ladders,Full-time,False,"Illinois, United States",2023-06-02 06:02:06,False,True,United States,year,115000.0,NaN,Discover Financial Services,['unix'],{'os': ['unix']}
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg.notna())]
# .notna is those withour na in it

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
180,Data Analyst,Data Analyst III,"Dos Palos, CA",via My ArkLaMiss Jobs,Full-time,False,"California, United States",2023-02-27 13:00:39,False,True,United States,year,90250.0,NaN,California Health & Wellness,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}"
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
988,Data Analyst,DATA ANALYST (ONSITE),"Springfield, MA",via Indeed,Full-time,False,"New York, United States",2023-11-21 13:00:13,False,False,United States,year,62623.0,NaN,Springfield Public Schools,"['sql', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr..."
1413,Data Analyst,Junior BI Developer,"Atlanta, GA",via Ai-Jobs.net,Full-time,False,Georgia,2023-10-31 13:57:41,False,True,United States,year,71300.0,NaN,Guidehouse,"['sql', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
784423,Data Analyst,Sales Data Analyst,"Juriquilla, Qro., Mexico",via Ai-Jobs.net,Full-time,False,Mexico,2023-01-05 06:43:20,False,False,Mexico,year,80850.0,NaN,Charger Logistics Inc,"['tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi']}"
784882,Data Analyst,Merchandising Analyst (Data Analyst),"Denton, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 15:29:24,False,False,United States,year,87500.0,NaN,Insight Global,"['sql', 'vba', 'tableau', 'excel', 'alteryx']","{'analyst_tools': ['tableau', 'excel', 'altery..."
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

##Clearing data

We want the date to be in the type datetime

In [ ]:
type(df.job_posted_date)

pandas.core.series.Series

In [ ]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

Add a new column with the job posted month

In [ ]:
df['job_posted_month']= df.job_posted_date.dt.month
#dont use df. to create new variable or modify

In [ ]:
df.info()
#check

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

Sorting

In [ ]:
df.sort_values(by = 'job_posted_date', inplace=True)
#inplace to store the sort order in the df, by = is optional

In [ ]:
df
# check

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",1
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,None,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,None,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,None,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,None,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,None,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,NaN,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,None,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,United States,None,NaN,NaN,VirtualVocations,None,None,12

Dropping column

In [ ]:
df.drop(labels = 'salary_hour_avg', axis = 1, inplace = True)
#axis = 1 means column, = 0 means row

In [ ]:
df.info()
#check

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 89.2+ MB

Remove row with na

In [ ]:
df.dropna(subset=['salary_year_avg'], inplace = True)
#removing the rows with salary year avg is na

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  datetime64[ns]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  object
 14  job_skills             20170 non-null  object
 15  job_type_skills        20170 non-null  object
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB

##Analysing data

Remeber to reinstall the dataset as we earlier delete some rows with na

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')

In [ ]:
df = dataset['train'].to_pandas()

checking data that is weird

In [ ]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [ ]:
df['salary_year_avg'].min()

15000.0

In [ ]:
min_salary = df['salary_year_avg'].idxmin()

In [ ]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

count of types of jobs

In [ ]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

now we want stats for a particular job type

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [ ]:
df.groupby(['job_title_short', 'job_country'])['salary_year_avg'].min().head(10)

job_title_short   job_country
Business Analyst  Afghanistan        NaN
                  Albania            NaN
                  Algeria            NaN
                  Angola             NaN
                  Argentina      63000.0
                  Armenia            NaN
                  Australia      63000.0
                  Austria            NaN
                  Azerbaijan         NaN
                  Bahamas            NaN
Name: salary_year_avg, dtype: float64

showing multiple operation at once

In [ ]:
df.groupby('job_title_short')[['salary_year_avg']].agg(['min', 'max', 'median', 'count'])

                          salary_year_avg
                                      min       max    median count
job_title_short
Business Analyst                  16500.0  387460.0   85000.0   610
Cloud Engineer                    42000.0  280000.0   90000.0    65
Data Analyst                      25000.0  650000.0   90000.0  5451
Data Engineer                     15000.0  525000.0  125000.0  4500
Data Scientist                    27000.0  960000.0  127500.0  5922
Machine Learning Engineer         30000.0  325000.0  106415.0   576
Senior Data Analyst               30000.0  425000.0  111175.0  1131
Senior Data Engineer              35000.0  425000.0  147500.0  1591
Senior Data Scientist             45000.0  890000.0  155500.0  1690
Software Engineer                 28000.0  375000.0   99150.0   467

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'median', 'count']).sort_values(by = 'median')

                               min       max    median  count
job_title_short
Business Analyst           16500.0  387460.0   85000.0    610
Cloud Engineer             42000.0  280000.0   90000.0     65
Data Analyst               25000.0  650000.0   90000.0   5451
Software Engineer          28000.0  375000.0   99150.0    467
Machine Learning Engineer  30000.0  325000.0  106415.0    576
Senior Data Analyst        30000.0  425000.0  111175.0   1131
Data Engineer              15000.0  525000.0  125000.0   4500
Data Scientist             27000.0  960000.0  127500.0   5922
Senior Data Engineer       35000.0  425000.0  147500.0   1591
Senior Data Scientist      45000.0  890000.0  155500.0   1690

In [ ]:
df[df['job_country'] == 'Brazil'].groupby('job_title_short').size()

job_title_short
Business Analyst              502
Cloud Engineer                220
Data Analyst                  599
Data Engineer                2303
Data Scientist                911
Machine Learning Engineer     223
Senior Data Analyst           138
Senior Data Engineer          846
Senior Data Scientist         303
Software Engineer             987
dtype: int64